name: Build Android APK (Capacitor auto)

on:
  workflow_dispatch: {}   # botón "Run workflow" en Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1) Instala deps y compila tu web (Vite)
      - name: Install deps & build web
        run: |
          npm ci || npm install
          npm run build

      # 2) Añade Capacitor si el proyecto no lo trae
      - name: Add Capacitor (if missing)
        run: |
          npm ls @capacitor/core || npm install @capacitor/core @capacitor/cli --save-exact
          if [ ! -f capacitor.config.ts ] && [ ! -f capacitor.config.json ]; then
            npx cap init "AIChef" "com.aichef.app" --web-dir=dist --no-input
          fi

      # 3) Genera plataforma Android (si no existe) y sincroniza
      - name: Capacitor sync
        run: |
          [ -d android ] || npx cap add android
          npx cap sync android

      # 4) JDK 17 + compilar con Gradle
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK (release, unsigned)
        run: |
          cd android
          ./gradlew assembleRelease
          ls -la app/build/outputs/apk/release

      # 5) Sube el APK como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          p
